name: Build

on:
  push:
    branches: 
      - master
      - feature/my-branch   # Add your branch name here
  pull_request:
    branches: 
      - master
      - feature/my-branch   # Add your branch name here
  workflow_dispatch:        # Allows manual trigger

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project files
        run: .\scripts\genprojects-win-vs.bat

      - name: Build ${{ matrix.config }} binaries
        run: cd build && msbuild /p:Configuration=${{ matrix.config }} OpenNeighborhood.sln

      - name: List build files
        run: dir build /s

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows-${{ matrix.config }}-Build
          path: build/

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y xorg-dev libgtk-3-dev

      - name: Generate project files
        run: ./scripts/genprojects-posix.sh

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}

      - name: List build files
        run: ls -R build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux-${{ matrix.config }}-Build
          path: build/

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Generate project files
        run: ./scripts/genprojects-posix.sh

      - name: Build ${{ matrix.config }} binaries
        run: cd build && make config=${{ matrix.config }}

      - name: List build files
        run: ls -R build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS-${{ matrix.config }}-Build
          path: build/